################################################################################
# File     : stdver.toml
# Author   : David Gussler
# Language : HDL-Registers TOML
#            https://hdl-registers.com/rst/user_guide/getting_started.html
# ==============================================================================
# Registers for the stdver, Standard Version, module. These Registers 
# should be instantiated at the base address of every FPGA design.
################################################################################


################################################################################
[scratchpad]
mode = "r_w"
description = "Scratchpad Register."

[scratchpad.scratchpad]
type = "bit_vector"
width = 32
default_value = "00010010001101000101011001111000"
description = """
Scratchpad that may be used for testing FPGA register access.

Default value = 0x12345678
"""


################################################################################
[id]
mode = "r"
description = "ID Register."

[id.id]
type = "bit_vector"
width = 32
description = "Unique identification number for this fpga."


################################################################################
[version]
mode = "r"
description = """
Version Register. [Semantic versioning](https://semver.org) is used.

Format: 0xZZAABBCC, where

- ZZ = build metadata

- AA = major version (0x00 to 0xFF)

- BB = minor version (0x00 to 0xFF)

- CC = patch version (0x00 to 0xFF)

If ZZ is anything other than 0x00, then
this indicates that the build is not a clean, official release build, but 
rather an engineering development build. This information is stored in the 
upper bits of the version register so that it is easy and obvious to tell when 
an official release build has not been loaded.
"""

[version.patch]
type = "integer"
max_value = 255
description = "Patch version - Backward compatible bug fix."

[version.minor]
type = "integer"
max_value = 255
description = "Minor version - Backward compatible new feature."

[version.major]
type = "integer"
max_value = 255
description = "Major version - Incompatible change."

[version.unused]
type = "bit_vector"
width = 5

[version.dev]
type = "bit"
description = """
1 = Development build. This build is for development and debugging, not for 
customer release or field use.

0 = Official release build.
"""

[version.local]
type = "bit"
description = """
1 = FPGA was built by local developer's PC.

0 = FPGA was built by CI server.
"""

[version.dirty]
type = "bit"
description = """
1 = FPGA was built from modified source files that were not checked in to
version control.

0 = FPGA was built from a clean repository.
"""


################################################################################
[date]
mode = "r"
description = """
Build Date Register - Date the FPGA was built, using the local timezone of
the computer the ran the build.

Format: BCD (Binary coded decimal) 0xYYYYMMDD, where

- YYYY = Build year (0 to 9999, but most likely 20XX ;) )

- MM   = Build month (0 to 12)

- DD   = Build day (0 to 31)
"""

[date.day]
type = "bit_vector"
width = 8
description = "Build Day."

[date.month]
type = "bit_vector"
width = 8
description = "Build Month."

[date.year]
type = "bit_vector"
width = 16
description = "Build Year."


################################################################################
[time]
mode = "r"
description = """
Build Time Register - Time the FPGA was built, using the local timezone of
the computer the ran the build.

Format: BCD (Binary coded decimal) 0x00HHMMSS, where

- 00 = Not used

- MM = Build hour (0 to 23)

- DD = Build minute (0 to 59)

- SS = Build second (0 to 59)
"""

[time.second]
type = "bit_vector"
width = 8
description = "Build Second."

[time.minute]
type = "bit_vector"
width = 8
description = "Build Minute."

[time.hour]
type = "bit_vector"
width = 8
description = "Build Hour."


################################################################################
[githash]
mode = "r"
description = "Git Hash Register."

[githash.githash]
type = "bit_vector"
width = 32
description = """
The 8 left-most characters of the last git hash for this repository.
"""
